### ISSUE TITLE
Unable to correctly deploy the backend application

### ISSUE THREAD

**Issue by syedmbzaidi** [technologiestiftung/giessdenkiez-de-dwd-harvester#40]
Hi,
Thanks for the reply. I have deployed the backend using terraform scripts. But the ECS task is not able to connect with databases. I have Terraform 0.13.5 . If I create a new task it ends and the following error can be found in cloudwatch.

Which version of Terraform is recommended? 

Secondly, I can see the S3, RDS resources being created. where is about **_DWD opendata FTP Radolan Radar data?_**

![image](https://user-images.githubusercontent.com/73298336/99900809-3af70480-2cb2-11eb-9f6f-efa3964debbd.png)

**Comment by ff6347** [comment]
Hi. When we deployed we used terraform 0.12

**Comment by ff6347** [comment]
> where is about DWD opendata FTP Radolan Radar data?

Can you explain a little further? The radolan data Congress from the dwd. Maybe @sebastian-meier can help a little?

**Comment by syedmbzaidi** [comment]
Hi,
The issue was resolved. There was an issue with the terraform script. The script was unable to create DB and tables for some reason. but this has been resolved. 
Thanks for your reply
